import * as THREE from 'three';

// ==========================================
// API ENDPOINTS
// ==========================================
export const API_ENDPOINTS = {
    predictSign: 'https://signova-ai-cvsw.onrender.com/api/auth/predict-sign/',
    speechToText: 'https://signova-ai-cvsw.onrender.com/api/auth/speech-to-text/',
};

// ==========================================
// THREE.JS CONFIGURATION
// ==========================================
export const SCENE_CONFIG = {
    backgroundColor: 0xf0f0f0,
};

export const CAMERA_CONFIG = {
    fov: 45,
    near: 0.1,
    far: 100,
    position: { x: 0, y: 1.4, z: 2.5 }
};

export const LIGHTS_CONFIG = {
    directional: {
        color: 0xffffff,
        intensity: 1.0,
        position: { x: 5, y: 10, z: 7.5 }
    },
    ambient: {
        color: 0xffffff,
        intensity: 0.4
    }
};

export const MODEL_CONFIG = {
    path: './assets/avatar.glb'
};

// ==========================================
// MEDIAPIPE CONFIG
// ==========================================
export const MEDIAPIPE_CONFIG = {
    stableTime: 1200,
    noHandTimeout: 2000,
    minDetectionConfidence: 0.7,
    minTrackingConfidence: 0.7,
};

// ==========================================
// ANIMATION SETTINGS
// ==========================================
export const LERP_FACTOR = 0.12;

// ==========================================
// POSE DEFINITIONS & HELPERS
// ==========================================

// REST POSE: RPM arms are in T-pose (spread out) by default.
export const REST_POSE = {
    RightArm:          { x: 1.4,  y: 0,    z: 0 },
    LeftArm:           { x: 1.4,  y: 0,    z: 0 },
    RightForeArm:      { x: 0.1,  y: 0,    z: 0 },
    LeftForeArm:       { x: 0.1,  y: 0,    z: 0 },
    RightHand:         { x: -0.1, y: 0,    z: 0 },
    RightHandThumb1:   { x: 0.3,  y: 0,    z: 0.4 },
    RightHandThumb2:   { x: 0.2,  y: 0,    z: 0 },
    RightHandIndex1:   { x: 0,    y: 0,    z: 0 },
    RightHandIndex2:   { x: 0,    y: 0,    z: 0 },
    RightHandIndex3:   { x: 0,    y: 0,    z: 0 },
    RightHandMiddle1:  { x: 0,    y: 0,    z: 0 },
    RightHandMiddle2:  { x: 0,    y: 0,    z: 0 },
    RightHandMiddle3:  { x: 0,    y: 0,    z: 0 },
    RightHandRing1:    { x: 0,    y: 0,    z: 0 },
    RightHandRing2:    { x: 0,    y: 0,    z: 0 },
    RightHandRing3:    { x: 0,    y: 0,    z: 0 },
    RightHandPinky1:   { x: 0,    y: 0,    z: 0 },
    RightHandPinky2:   { x: 0,    y: 0,    z: 0 },
    RightHandPinky3:   { x: 0,    y: 0,    z: 0 },
};

// HELPER: build a fully-curled fist object
export function fist() {
    return {
        RightHandIndex1: { x: 1.5, y: 0, z: 0 },
        RightHandIndex2: { x: 1.2, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
    };
}

// Helper: open flat hand
export function flatHand() {
    return {
        RightHandIndex1: { x: 0, y: 0, z: 0 },
        RightHandIndex2: { x: 0, y: 0, z: 0 },
        RightHandIndex3: { x: 0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 0, y: 0, z: 0 },
        RightHandMiddle2:{ x: 0, y: 0, z: 0 },
        RightHandMiddle3:{ x: 0, y: 0, z: 0 },
        RightHandRing1:  { x: 0, y: 0, z: 0 },
        RightHandRing2:  { x: 0, y: 0, z: 0 },
        RightHandRing3:  { x: 0, y: 0, z: 0 },
        RightHandPinky1: { x: 0, y: 0, z: 0 },
        RightHandPinky2: { x: 0, y: 0, z: 0 },
        RightHandPinky3: { x: 0, y: 0, z: 0 },
    };
}

// Arm raised to signing position
export function signingArm() {
    return {
        RightArm:     { x: 0.0, y: -0.3, z: 0 },
        RightForeArm: { x: -1.3, y: 0, z: 0 },
        RightHand:    { x: 0.1, y: 0, z: 0 },
    };
}

// ==========================================
// SIGN LANGUAGE MAP
// ==========================================
export const signLanguageMap = {
    A: {
        ...signingArm(),
        ...fist(),
        RightHandThumb1: { x: 0.3, y: 0,   z: 0.3 },
        RightHandThumb2: { x: 0.3, y: 0,   z: 0 },
    },
    B: {
        ...signingArm(),
        ...flatHand(),
        RightHandThumb1: { x: 0.2, y: 0,   z: 1.0 },
        RightHandThumb2: { x: 0.8, y: 0,   z: 0 },
    },
    C: {
        ...signingArm(),
        RightHandIndex1: { x: 0.7, y: 0, z: 0 },
        RightHandIndex2: { x: 0.5, y: 0, z: 0 },
        RightHandIndex3: { x: 0.3, y: 0, z: 0 },
        RightHandMiddle1:{ x: 0.7, y: 0, z: 0 },
        RightHandMiddle2:{ x: 0.5, y: 0, z: 0 },
        RightHandMiddle3:{ x: 0.3, y: 0, z: 0 },
        RightHandRing1:  { x: 0.7, y: 0, z: 0 },
        RightHandRing2:  { x: 0.5, y: 0, z: 0 },
        RightHandRing3:  { x: 0.3, y: 0, z: 0 },
        RightHandPinky1: { x: 0.7, y: 0, z: 0 },
        RightHandPinky2: { x: 0.5, y: 0, z: 0 },
        RightHandPinky3: { x: 0.3, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.6 },
        RightHandThumb2: { x: 0.4, y: 0, z: 0 },
    },
    D: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0, z: 0 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.4, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.4, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.4, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.7 },
        RightHandThumb2: { x: 0.6, y: 0, z: 0 },
    },
    E: {
        ...signingArm(),
        RightHandIndex1: { x: 0.5, y: 0, z: 0 },
        RightHandIndex2: { x: 1.4, y: 0, z: 0 },
        RightHandIndex3: { x: 0.8, y: 0, z: 0 },
        RightHandMiddle1:{ x: 0.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.4, y: 0, z: 0 },
        RightHandMiddle3:{ x: 0.8, y: 0, z: 0 },
        RightHandRing1:  { x: 0.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.4, y: 0, z: 0 },
        RightHandRing3:  { x: 0.8, y: 0, z: 0 },
        RightHandPinky1: { x: 0.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 0.8, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 1.1 },
        RightHandThumb2: { x: 0.9, y: 0, z: 0 },
    },
    F: {
        ...signingArm(),
        RightHandIndex1: { x: 1.0, y: 0, z: 0 },
        RightHandIndex2: { x: 0.8, y: 0, z: 0 },
        RightHandIndex3: { x: 0.3, y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle2:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle3:{ x: 0,   y: 0, z: 0 },
        RightHandRing1:  { x: 0,   y: 0, z: 0 },
        RightHandRing2:  { x: 0,   y: 0, z: 0 },
        RightHandRing3:  { x: 0,   y: 0, z: 0 },
        RightHandPinky1: { x: 0,   y: 0, z: 0 },
        RightHandPinky2: { x: 0,   y: 0, z: 0 },
        RightHandPinky3: { x: 0,   y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.8 },
        RightHandThumb2: { x: 0.7, y: 0, z: 0 },
    },
    G: {
        RightArm:     { x: 0.0, y: 0, z: 0 },
        RightForeArm: { x: -1.3, y: 0.5, z: 0 },
        RightHand:    { x: 0.1, y: 0, z: 0.3 },
        RightHandIndex1: { x: 0,   y: 0, z: -0.2 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.4, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.4, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.4, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.2, y: 0, z: 0.3 },
        RightHandThumb2: { x: 0.1, y: 0, z: 0 },
    },
    H: {
        RightArm:     { x: 0.0, y: 0, z: 0 },
        RightForeArm: { x: -1.3, y: 0.5, z: 0 },
        RightHand:    { x: 0.1, y: 0, z: 0.3 },
        RightHandIndex1: { x: 0,   y: 0, z: -0.1 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: 0.1 },
        RightHandMiddle2:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle3:{ x: 0,   y: 0, z: 0 },
        RightHandRing1:  { x: 1.4, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.4, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.8 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    I: {
        ...signingArm(),
        RightHandIndex1: { x: 1.5, y: 0, z: 0 },
        RightHandIndex2: { x: 1.2, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 0,   y: 0, z: 0 },
        RightHandPinky2: { x: 0,   y: 0, z: 0 },
        RightHandPinky3: { x: 0,   y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.9 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    J: {
        ...signingArm(),
        RightForeArm: { x: -1.3, y: 0.5, z: 0 },
        RightHand:    { x: 0.1, y: 0.4, z: -0.3 },
        RightHandIndex1: { x: 1.5, y: 0, z: 0 },
        RightHandIndex2: { x: 1.2, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 0,   y: 0, z: 0 },
        RightHandPinky2: { x: 0,   y: 0, z: 0 },
        RightHandPinky3: { x: 0,   y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.9 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    K: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0, z: 0 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: 0.3 },
        RightHandMiddle2:{ x: 0.5, y: 0, z: 0 },
        RightHandMiddle3:{ x: 0.3, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.5 },
        RightHandThumb2: { x: 0.4, y: 0, z: 0 },
    },
    L: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0, z: 0 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.1, y: 0, z: -0.3 },
        RightHandThumb2: { x: 0.1, y: 0, z: 0 },
    },
    M: {
        ...signingArm(),
        RightHandIndex1: { x: 1.0, y: 0, z: 0 },
        RightHandIndex2: { x: 1.3, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.0, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.3, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.0, y: 0, z: 0 },
        RightHandRing2:  { x: 1.3, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.4, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 1.2 },
        RightHandThumb2: { x: 0.8, y: 0, z: 0 },
    },
    N: {
        ...signingArm(),
        RightHandIndex1: { x: 1.0, y: 0, z: 0 },
        RightHandIndex2: { x: 1.3, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.0, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.3, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 1.2 },
        RightHandThumb2: { x: 0.8, y: 0, z: 0 },
    },
    O: {
        ...signingArm(),
        RightHandIndex1: { x: 1.0, y: 0, z: 0 },
        RightHandIndex2: { x: 0.8, y: 0, z: 0 },
        RightHandIndex3: { x: 0.4, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.0, y: 0, z: 0 },
        RightHandMiddle2:{ x: 0.8, y: 0, z: 0 },
        RightHandMiddle3:{ x: 0.4, y: 0, z: 0 },
        RightHandRing1:  { x: 1.0, y: 0, z: 0 },
        RightHandRing2:  { x: 0.8, y: 0, z: 0 },
        RightHandRing3:  { x: 0.4, y: 0, z: 0 },
        RightHandPinky1: { x: 1.0, y: 0, z: 0 },
        RightHandPinky2: { x: 0.7, y: 0, z: 0 },
        RightHandPinky3: { x: 0.3, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.7 },
        RightHandThumb2: { x: 0.8, y: 0, z: 0 },
    },
    P: {
        RightArm:     { x: 0.0, y: 0,   z: 0 },
        RightForeArm: { x: -0.5, y: 1.0, z: 0 },
        RightHand:    { x: 0.5, y: 0,   z: 0 },
        RightHandIndex1: { x: 0,   y: 0, z: 0 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: 0.3 },
        RightHandMiddle2:{ x: 0.5, y: 0, z: 0 },
        RightHandMiddle3:{ x: 0.3, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.5 },
        RightHandThumb2: { x: 0.4, y: 0, z: 0 },
    },
    Q: {
        RightArm:     { x: 0.0, y: 0,   z: 0 },
        RightForeArm: { x: -0.5, y: 1.0, z: 0 },
        RightHand:    { x: 0.4, y: 0,   z: 0.3 },
        RightHandIndex1: { x: 0,   y: 0, z: 0 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.4, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.4, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.4, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.2, y: 0, z: 0.3 },
        RightHandThumb2: { x: 0.1, y: 0, z: 0 },
    },
    R: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0,  z: -0.2 },
        RightHandIndex2: { x: 0,   y: 0,  z: 0 },
        RightHandIndex3: { x: 0,   y: 0,  z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0,  z: -0.4 },
        RightHandMiddle2:{ x: 0,   y: 0,  z: 0 },
        RightHandMiddle3:{ x: 0,   y: 0,  z: 0 },
        RightHandRing1:  { x: 1.5, y: 0,  z: 0 },
        RightHandRing2:  { x: 1.2, y: 0,  z: 0 },
        RightHandRing3:  { x: 1.0, y: 0,  z: 0 },
        RightHandPinky1: { x: 1.5, y: 0,  z: 0 },
        RightHandPinky2: { x: 1.2, y: 0,  z: 0 },
        RightHandPinky3: { x: 1.0, y: 0,  z: 0 },
        RightHandThumb1: { x: 0.3, y: 0,  z: 0.8 },
        RightHandThumb2: { x: 0.5, y: 0,  z: 0 },
    },
    S: {
        ...signingArm(),
        ...fist(),
        RightHandThumb1: { x: 0.3, y: 0, z: 0.8 },
        RightHandThumb2: { x: 0.7, y: 0, z: 0 },
    },
    T: {
        ...signingArm(),
        RightHandIndex1: { x: 1.2, y: 0, z: 0 },
        RightHandIndex2: { x: 1.2, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.2, y: 0, z: 0.9 },
        RightHandThumb2: { x: 0.3, y: 0, z: 0 },
    },
    U: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0, z: 0.1 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: -0.1 },
        RightHandMiddle2:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle3:{ x: 0,   y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.8 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    V: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0, z: 0.3 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: -0.3 },
        RightHandMiddle2:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle3:{ x: 0,   y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.8 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    W: {
        ...signingArm(),
        RightHandIndex1: { x: 0,   y: 0, z: 0.4 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle2:{ x: 0,   y: 0, z: 0 },
        RightHandMiddle3:{ x: 0,   y: 0, z: 0 },
        RightHandRing1:  { x: 0,   y: 0, z: -0.4 },
        RightHandRing2:  { x: 0,   y: 0, z: 0 },
        RightHandRing3:  { x: 0,   y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.7 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    X: {
        ...signingArm(),
        RightHandIndex1: { x: 0.5, y: 0, z: 0 },
        RightHandIndex2: { x: 1.4, y: 0, z: 0 },
        RightHandIndex3: { x: 0.8, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.7 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
    Y: {
        ...signingArm(),
        RightHandIndex1: { x: 1.5, y: 0, z: 0 },
        RightHandIndex2: { x: 1.2, y: 0, z: 0 },
        RightHandIndex3: { x: 1.0, y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 0,   y: 0, z: -0.2 },
        RightHandPinky2: { x: 0,   y: 0, z: 0 },
        RightHandPinky3: { x: 0,   y: 0, z: 0 },
        RightHandThumb1: { x: 0.1, y: 0, z: -0.4 },
        RightHandThumb2: { x: 0.1, y: 0, z: 0 },
    },
    Z: {
        ...signingArm(),
        RightForeArm: { x: -1.3, y: 0.3, z: 0 },
        RightHand:    { x: 0.1, y: -0.4, z: 0 },
        RightHandIndex1: { x: 0,   y: 0, z: 0 },
        RightHandIndex2: { x: 0,   y: 0, z: 0 },
        RightHandIndex3: { x: 0,   y: 0, z: 0 },
        RightHandMiddle1:{ x: 1.5, y: 0, z: 0 },
        RightHandMiddle2:{ x: 1.2, y: 0, z: 0 },
        RightHandMiddle3:{ x: 1.0, y: 0, z: 0 },
        RightHandRing1:  { x: 1.5, y: 0, z: 0 },
        RightHandRing2:  { x: 1.2, y: 0, z: 0 },
        RightHandRing3:  { x: 1.0, y: 0, z: 0 },
        RightHandPinky1: { x: 1.5, y: 0, z: 0 },
        RightHandPinky2: { x: 1.2, y: 0, z: 0 },
        RightHandPinky3: { x: 1.0, y: 0, z: 0 },
        RightHandThumb1: { x: 0.3, y: 0, z: 0.8 },
        RightHandThumb2: { x: 0.5, y: 0, z: 0 },
    },
};
